language: node_js
node_js: 11.14
jobs:
  include:
    - stage: test
      script: npm run lint .
    - stage: deploy to GH pages
      script: npx webpack --mode=production
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: public
        on:
          branch: master
